package telas;

import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JDesktopPane();
        btnRelatorio = new javax.swing.JButton();
        btnNovaVenda = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        btnCadastrarCliente = new javax.swing.JButton();
        lblNovaVenda = new javax.swing.JLabel();
        lblRelatorio = new javax.swing.JLabel();
        btnCatalogo = new javax.swing.JButton();
        lblCatalogo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroCliente = new javax.swing.JMenuItem();
        menuCadastroFuncionario = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        menuSistemaSobre = new javax.swing.JMenuItem();
        menuSistemaSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);

        painel.setBackground(new java.awt.Color(51, 0, 255));

        btnRelatorio.setText("<IMAGEN-RELATÓRIO>");
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.setMaximumSize(new java.awt.Dimension(85, 85));
        btnRelatorio.setMinimumSize(new java.awt.Dimension(85, 85));

        btnNovaVenda.setText("<IMAGEM-VENDA>");
        btnNovaVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovaVenda.setMaximumSize(new java.awt.Dimension(85, 85));
        btnNovaVenda.setMinimumSize(new java.awt.Dimension(85, 85));

        lblCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCliente.setText("CLIENTE");

        btnCadastrarCliente.setText("<IMAGEM-CLIENTE>");
        btnCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarCliente.setMaximumSize(new java.awt.Dimension(85, 85));
        btnCadastrarCliente.setMinimumSize(new java.awt.Dimension(85, 85));

        lblNovaVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNovaVenda.setText("NOVA VENDA");

        lblRelatorio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRelatorio.setText("RELATÓRIO");

        btnCatalogo.setText("<IMAGEN-CATÁLOGO>");
        btnCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatalogo.setMaximumSize(new java.awt.Dimension(85, 85));
        btnCatalogo.setMinimumSize(new java.awt.Dimension(85, 85));

        lblCatalogo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCatalogo.setText("CATALOGO");

        painel.setLayer(btnRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(btnNovaVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(lblCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(btnCadastrarCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(lblNovaVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(lblRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(btnCatalogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(lblCatalogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblNovaVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRelatorio)
                .addGap(92, 92, 92))
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                        .addComponent(lblCatalogo)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(lblCatalogo))
                .addGap(13, 13, 13)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRelatorio))
                .addGap(112, 112, 112))
        );

        menuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuCadastro.setText("Cadastros");
        menuCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuCadastroCliente.setText("Cliente");
        menuCadastro.add(menuCadastroCliente);

        menuCadastroFuncionario.setText("Funcionário");
        menuCadastroFuncionario.setEnabled(false);
        menuCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroFuncionario);

        menuBar.add(menuCadastro);

        menuSistema.setText("Sistema");
        menuSistema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuSistemaSobre.setText("Sobre");
        menuSistemaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSistemaSobreActionPerformed(evt);
            }
        });
        menuSistema.add(menuSistemaSobre);

        menuSistemaSair.setText("Sair");
        menuSistemaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSistemaSairActionPerformed(evt);
            }
        });
        menuSistema.add(menuSistemaSair);

        menuBar.add(menuSistema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Item de menu para sair do sistema
    private void menuSistemaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSistemaSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(this,"Deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(sair);
        }
    }//GEN-LAST:event_menuSistemaSairActionPerformed
    
    //Item de menu para saber sobre o sistema   
    private void menuSistemaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSistemaSobreActionPerformed
        JOptionPane.showMessageDialog(this, "Desenvolvido por\n\nAdelly Lima\nRenato Lélis\nYanka Santos\n\nProfessor : Melo","Sobre",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuSistemaSobreActionPerformed
    
    // Botão para chamar a tela de cadastro de um funcionario
    private void menuCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFuncionarioActionPerformed
        TelaFuncionario funcionario = new TelaFuncionario();
        funcionario.setVisible(true);
        painel.add(funcionario);
    }//GEN-LAST:event_menuCadastroFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel lblCatalogo;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblNovaVenda;
    private javax.swing.JLabel lblRelatorio;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroCliente;
    public static javax.swing.JMenuItem menuCadastroFuncionario;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenuItem menuSistemaSair;
    private javax.swing.JMenuItem menuSistemaSobre;
    private javax.swing.JDesktopPane painel;
    // End of variables declaration//GEN-END:variables
}
